rehypejs/rehype

packages/rehype-parse/index.js, test/fixtures/position-false/config.json, test/fixtures/position-false/index.html, test/fixtures/position-false/index.json
If `settings.position` is false, `position` attribute of each node won't be set.
=> Add position option

doc/plugins.md
This plugin has been working well for us (enabling us to use [highlights](https://github.com/atom/highlights) during builds). Thought it might prove useful to others.
=> Add rehype-highlight-code-block

doc/plugins.md
I just released a version that uses refractor under the hood.
=> Add rehype-prism to plugins list

readme.md
This project looks rehype, however the link points retext's plugins list. I fixed this.
Thank you.
=> Fix `plugins` url in `README.md`

doc/plugins.md
Syntax highlight code blocks using [Shiki](https://github.com/octref/shiki/). 
> It uses TextMate grammar to tokenize strings, and colors the tokens with VS Code themes. ~ http://shiki.matsu.io/
=> add rehype-shiki plugin to docs

doc/plugins.md
Added two additional plugins to the list
*   [rehype-inline-svg](https://github.com/JS-DevTools/rehype-inline-svg) — Inlines and optimizes SVG images
*   [rehype-toc](https://github.com/JS-DevTools/rehype-toc) — Adds a table of contents (TOC) to the page
=> Added rehype-inline-svg and rehype-toc

doc/plugins.md
I recently published a new transformer plugin for rehype which allows you to truncate HTML. I thought this might be of use to others so I've added a reference to it in your plugin documentation.
=> Add `rehype-truncate` to list of plugins

doc/plugins.md
Add [rehype-inline](https://github.com/marko-knoebl/rehype-inline) to the list of plugins. Rehype-inline can inline css, js and images into HTML
=> Add `rehype-inline` to list of plugins

doc/plugins.md
As I couldn't get gatsby-remark-a11y-emoji working with gatsby-plugin-mdx I made this rehype version to make emojis accessible by wrapping them in a <span role="image"> with aria-label set to the emojis description based on gemoji.
=> Add `rehype-accessible-emojis` to list of plugins

doc/plugins.md
In the "Creating plugins" section, the link to the "Create a plugin" guide is a 404.
This corrects the link URL to `https://unifiedjs.com/learn/guide/create-a-plugin/`
=> Correct the link URL to "Create a plugin" guide

packages/rehype-stringify/index.d.ts
On TypeScript 4.3.5 & `remark-stringify` 9.0.0 I get:
> error TS1046: Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier
Adding an `export` seems to make it happy
=> stringify: fix parse error in types

packages/rehype-parse/index.d.ts
*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [x] If applicable, I’ve added docs and tests
```bash
node_modules/rehype-parse/index.d.ts:5:1 - error TS1046: Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier.
5 const rehypeParse: Plugin<[Options] | [], Root, string>
~~~~~
```
Same error existed in rehype-stringify and was fixed by #62 
Applied same fix to index.d.ts in rehype-parse.
=> parse: fix parse error in types

doc/plugins.md
I wrote a [plugin](https://github.com/viktor-yakubiv/rehype-postcss) that runs PostCSS on `<style>` nodes and `style` attributes in the rehype tree and would like to add it to the list. Thank you in advance 🙂
=> Add `rehype-postcss` to list of plugins

doc/plugins.md
I created a rehype plugin that utilises the lodash.template function and substitutes values from the dictionary instead of template strings in text and properties in the document. I wrote very basic implementation that is enough for me at the moment and will cover most of the cases but has some limitations (you can find in in the read-me and a test file).
Currently, I would like to publish my package and add it to the list alongside of others. I found that `rehype-template` is already taken. I was also worried that this could be misleading as _template_ is a very generic thing. I would like to discuss with you the best name, publish a package and add it here. My options are `rehype-lodash-template` and `rehype-substitude` but I am open to any name; I will rename the repository, package …
=> Add `rehype-lodash-template` to list of plugin

doc/plugins.md
As part of a requirement moving from a blog from Gatsby to NextJS (powered by a unist/remark/rehype chain), [I needed a way to create custom IDs from the heading's text](https://github.com/rehypejs/rehype-slug/issues/10). The feature was (entirely understandably) rejected from `rehype-slug`, so I created a custom package with this functionality.
This PR adds said package to the list of `rehype` utilities.
=> Add `rehype-slug-custom-id` to list of plugins

doc/plugins.md
Added `rehype-jargon` to the list plugins. Used to be a `remark` plugin but it's not a `rehype` plugin. The other version is no more available.
=> Add `rehype-jargon` to list of plugins

doc/plugins.md
A `rehype` plugin to extract meta data from an HTML document.
=> Add `rehype-extract-meta` to list of plugins

packages/rehype-cli/tsconfig.json, tsconfig.json
Additionally scopes JSON module to the one (CJS) location where it is used.
=> Update `tsconfig.json` to use use node16 module resolution

doc/plugins.md
The rehype-section was not maintained.
Therefore, this plugin was created to add the id of the heading to the section.
=> Add `rehype-sectionize` to list of plugins

doc/plugins.md
Added a new rehype plugin to the list at `doc/plugins.md`
=> Add rehype-color-chips to the list of plugins

doc/plugins.md
adding link to new plugin
ref: https://github.com/rehypejs/rehype-minify/pull/47
=> docs: add link to rehype remove images

doc/plugins.md
Add new 'scroll to top' plugin
Add a new Rehype plugin to the plugins doc. `rehype-scroll-to-top`.
=> Add `rehype-scroll-to-top`, `rehype-smenatic-images` to list of plugins

doc/plugins.md
Added a new plugin **`rehype-highlight-code-lines`** to list of plugins
https://github.com/ipikuka/rehype-highlight-code-lines
https://www.npmjs.com/package/rehype-highlight-code-lines
It is `rehype plugin` to add container to each code line in a code block, allowing numbering of the code block and highlighting desired lines of code.
The `rehype-highlight-code-lines` works with `rehype-highlight` well; and should be used after `rehype-highlight` in the plugin chain. The `rehype-highlight-code-lines` also works with other code highlighters that have no line numbering and line highlighting features.
**A snapshot from a working app:**
=> Add `rehype-highlight-code-lines` to list of plugins

doc/plugins.md
Added a new plugin [`rehype-callouts`](https://github.com/lin-stephanie/rehype-callouts) to list of plugins
=> Add `rehype-callouts` to list of plugins

license, packages/rehype-cli/license, packages/rehype-parse/license, packages/rehype-stringify/license, packages/rehype/license
closes #179
Removed license year from license file.
Added license files to packages
=> Add license file to packages

doc/plugins.md
When a page contains a large number of katex formulas, if we want to use a tool to translate the webpage (such as the built-in translation tool of Google Chrome), the translation tool will often translate the symbols in the katex block, which will cause the formula to be destroyed.
So I wrote a rehype plugin [rehype-katex-notranslate](https://www.npmjs.com/package/rehype-katex-notranslate). This plugin add the attribute translate="no" to the katex formula generated by rehype-katex to prevent the formulas from being recognized and translated by webpage and browser translation tools.
=> [add] add rehype-katex-notranslate plugin for docs

doc/plugins.md
Add [`rehype-mathml`](https://github.com/Daiji256/rehype-mathml) to list of plugins
Rendering math with MathML is lightweight and supported by many browsers.
I wanted a plugin for rendering math with MathML, similar to `rehype-mathjax` and `rehype-katex`, so I have created `rehype-mathml`.
npm: [`@daiji256/rehype-mathml`](https://www.npmjs.com/package/@daiji256/rehype-mathml)
=> Add `rehype-mathml` to list of plugins

doc/plugins.md
Added a rehype plugin into the plugins.md file.
=> feat: Added a new rehype plugin to plugins.md

doc/plugins.md
Add `rehype-graphviz-diagram` to plugin list. The `rehype-graphviz-diagram` is the wrapper for [graphviz](https://graphviz.org/) used for integrating with unified.
It allows your insert diagrams in markdown or html content. 
Here is the [README file](https://github.com/PrinOrange/rehype-graphviz-diagram). And plugin effect,
=> Add `rehype-graphviz-diagram`
